### ISSUE TITLE
About the Instructions for installation on linux

### ISSUE THREAD

**Issue by SolaireZ** [pabloprf/MITIM-fusion#25]
Hey there! It seems that in the recent updates of main branch, `setup.py` is replaces by the  `pyproject.toml `, and ` setuptools` is used as the backend.

When I install the MITIM 2.1.0, in the instructions for installation
`pip3 install -e MITIM-fusion[pyqt]` should be replaced by `pip3 install -e .` or  `pip3 install -e .[pyqt,omfit,nn]` for optional dependencies (ubuntu 22. 04 LTS, bash shell ) and in macOS (sonoma)  zsh shell `pip3 install -e .\[pyqt,omfit,nn\]`

I believe you have also noticed this, just a reminder.

**Comment by pabloprf** [comment]
Hi!
`pip3 install -e MITIM-fusion` should work if you're pointing to the folder where you cloned the repo, `MITIM-fusion`.
`pip3 install -e .` should work if you're already inside the cloned folder, i.e. `cd MITIM-fusion/`.
As per the need for `\`, that's if you're using ZSH (as by default in Macs), and that's in the [FAQ](https://mitim-fusion.readthedocs.io/en/latest/faq.html) under "Square brackets not understood by shell"

**Comment by SolaireZ** [comment]
> Hi! `pip3 install -e MITIM-fusion` should work if you're pointing to the folder where you cloned the repo, `MITIM-fusion`. `pip3 install -e .` should work if you're already inside the cloned folder, i.e. `cd MITIM-fusion/`. As per the need for `\`, that's if you're using ZSH (as by default in Macs), and that's in the [FAQ](https://mitim-fusion.readthedocs.io/en/latest/faq.html) under "Square brackets not understood by shell"

Oh, my mistake! I remembered it works good when I installed the previous edition. I didn't realize I changed the path.
Should checked it carefully.
Thank you for your kindly reply.

**Comment by pabloprf** [comment]
Sure no worries! glad it's clear now
