### ISSUE TITLE
 GA omega cluster pyqt issues. 

### ISSUE THREAD

**Issue by jmcclena** [pabloprf/MITIM-fusion#26]
Dmitri Orlov and I are trying to install MITIM on the GA omega cluster. MITIM gets successfully built. However, when I run the regression test: 
```
module purge
module load python/3.11
source mitim-env/bin/activate
python3 MITIM-fusion/tests/OPT_workflow.py
```

I get the following error
```
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland, offscreen, minimal, vkkhrdisplay, linuxfb, xcb, vnc, minimalegl, wayland-egl, eglfs.

```

@pabloprf any idea what might cause this?

**Comment by pabloprf** [comment]
That's related to the `pyqt` python package, which is used in MITIM for visualizing outputs in a notebook-style plot.
That package fails if the machine does not allow that type of interactive GUIs. Usually in clusters I don't recommend to run MITIM with the `pyqt` package.
I made the framework such that any other functionality still works without it, it will just not be able to show the default MITIM plots.
I don't know how to debug `pyqt` or the `Qt` plugin in OMEGA, as I don't fully understand how it really works in the back.

**Comment by pabloprf** [comment]
Unfortunately, all ready-to-go plotting routines do use at some point pyqt notebooks.
In a lot of the scripts, I define the notebooks with pyqt, which then provide figure objects that can be used with normal matplotlib methods. One could extract the figures without necessarily plotting into a fig generated by the pyqt notebook, but that's not already done by default, generally.
